version: '3.2'

services:
  tf-jupyter:
    image: guangchenj/cuda11.6.0-devel-ubuntu20.04:latest
    container_name: cuda11.6.0-devel-ubuntu20.04
#    build:
#      context: .
#      dockerfile: ./Dockerfile
    privileged: true
    tty: true
    stdin_open: true
    command:
      - sh
      - -c
      - |
          # change password
          passwd << EOD
          ${pwd}
          ${pwd}
          EOD
          # copy the config file
          cp /etc/ssh/sshd_config /etc/ssh/sshd_config.bak
          # Password is required for SSH connection
          sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/g' /etc/ssh/sshd_config
          # Start the ssh service
          service ssh start
    restart: always
    shm_size: '8gb'
    volumes:
      - "/data/cuda-dev:/cuda-dev"
    ports:
      - "8122:22"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    networks:
      net:
        aliases:
          - cuda11.6.0-devel-ubuntu20.04

networks:
  net:
    driver: bridge

